development:
  adapter: postgresql
  database: sparc_data
  host: localhost
  username: rwb3y
  password: 

test:
  adapter: postgresql
  database: rails_test
  host: localhost
  username: root
  password:

production:
  adapter: postgresql
  database: sparc_data
  username: 
  password: 
